version: "3.5"

services:
  api:
    build: .
    env_file:
      - .env
    # command: uvicorn src.main:app --host 0.0.0.0 --limit-max-requests 250 --workers 8 --log-level debug
    restart: unless-stopped
    ports:
      - "16120:80"
    environment:
      - MODULE_NAME=src.main
      - TIMEOUT=600
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
        max-file: "5"
